<?php return array (
  'well_register' => 'App\\Services\\BigData\\Forms\\WellRegister',
  'fluid_production' => 'App\\Services\\BigData\\Forms\\FluidProduction',
  'production_well' => '\\App\\Services\\BigData\\Forms\\ProductionWell',
  'kpc' => '\\App\\Services\\BigData\\Forms\\Kpc',
  'injection_wells' => '\\App\\Services\\BigData\\Forms\\InjectionWells',
  'well_exploitation' => '\\App\\Services\\BigData\\Forms\\WellExploitation',
  'gtm_register' => '\\App\\Services\\BigData\\Forms\\GtmRegister',
  'well_design' => '\\App\\Services\\BigData\\Forms\\WellDesign',
  'prs' => '\\App\\Services\\BigData\\Forms\\Prs',
  'gas_well' => '\\App\\Services\\BigData\\Forms\\GasWell',
  'daily_drill' => '\\App\\Services\\BigData\\Forms\\DailyDrill',
  'well_constr' => '\\App\\Services\\BigData\\Forms\\WellConstr',
  'tech_state' => '\\App\\Services\\BigData\\Forms\\TechState',
  'bottom_hole' => '\\App\\Services\\BigData\\Forms\\BottomHole',
);