<?php

namespace App\Imports;

use App\Models\DZO\DZOdaily;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithStartRow;
use Illuminate\Contracts\Queue\ShouldQueue;
use Maatwebsite\Excel\Concerns\WithChunkReading;

class DZOdayImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new DZOdaily([
            "date" => \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($row[ 0 ]),
            "dzo" => $row[ 1 ],
            "mestorozhdenie" => $row[ 2 ],
            "ngdu" => $row[ 3 ],
            "oil_plan" => $row[ 4 ],
            "oil_fact" => $row[ 5 ],
            "gk_plan" => $row[ 6 ],
            "gk_fact" => $row[ 7 ],
            "dobycha_zhidkosti_plan" => $row[ 8 ],
            "dobycha_zhidkosti_fact" => $row[ 9 ],
            "sdacha_nefti_kuun" => $row[ 10 ],
            "oil_dlv_plan" => $row[ 11 ],
            "oil_dlv_fact" => $row[ 12 ],
            "tovarnyi_ostatok_nefti_prev_day" => $row[ 13 ],
            "tovarnyi_ostatok_nefti_today" => $row[ 14 ],
            "dobycha_gaza_prirod_plan" => $row[ 15 ],
            "dobycha_gaza_prirod_fact" => $row[ 16 ],
            "sdacha_gaza_prirod_plan" => $row[ 17 ],
            "sdacha_gaza_prirod_fact" => $row[ 18 ],
            "raskhod_prirod_plan" => $row[ 19 ],
            "raskhod_prirod_fact" => $row[ 20 ],
            "pererabotka_gaza_prirod_plan" => $row[ 21 ],
            "pererabotka_gaza_prirod_fact" => $row[ 22 ],
            "dobycha_gaza_poput_plan" => $row[ 23 ],
            "dobycha_gaza_poput_fact" => $row[ 24 ],
            "sdacha_gaza_poput_plan" => $row[ 25 ],
            "sdacha_gaza_poput_fact" => $row[ 26 ],
            "raskhod_poput_plan" => $row[ 27 ],
            "raskhod_poput_fact" => $row[ 28 ],
            "raskhod_syraya_poput_plan" => $row[ 29 ],
            "raskhod_syraya_poput_fact" => $row[ 30 ],
            "raskhod_syraya_tovarnaya_plan" => $row[ 31 ],
            "raskhod_tovarnaya_poput_fact" => $row[ 32 ],
            "pererabotka_gaza_poput_plan" => $row[ 33 ],
            "pererabotka_gaza_poput_fact" => $row[ 34 ],
            "poput_tech_poteri" => $row[ 35 ],
            "poput_razresheno_sjiganie" => $row[ 36 ],
            "ppd_zakachka_morskoi_vody_plan" => $row[ 37 ],
            "ppd_zakachka_morskoi_vody_fact" => $row[ 38 ],
            "ppd_zakachka_stochnoi_vody_plan" => $row[ 39 ],
            "ppd_zakachka_stochnoi_vody_fact" => $row[ 40 ],
            "ppd_zakachka_albsen_vody_plan" => $row[ 41 ],
            "ppd_zakachka_albsen_vody_fact" => $row[ 42 ],
            "ppd_zakachka_gaza_plan" => $row[ 43 ],
            "ppd_zakachka_gaza_fact" => $row[ 44 ],
            "ppd_zakachka_plast_poput_vody_plan" => $row[ 45 ],
            "ppd_zakachka_plast_poput_vody_fact" => $row[ 46 ],
            "ppd_zakachka_plast_apsk_vody_plan" => $row[ 47 ],
            "ppd_zakachka_plast_apsk_vody_fact" => $row[ 48 ],
            "ppd_zakachka_voljskoy_vody_plan" => $row[ 49 ],
            "ppd_zakachka_voljskoy_vody_fact" => $row[ 50 ],
            "ppd_zakachka_senopal_vody_plan" => $row[ 51 ],
            "ppd_zakachka_senopal_vody_fact" => $row[ 52 ],
            "otm_iz_burenia_skv_plan" => $row[ 53 ],
            "otm_iz_burenia_skv_fact" => $row[ 54 ],
            "otm_burenie_prohodka_plan" => $row[ 55 ],
            "otm_burenie_prohodka_fact" => $row[ 56 ],
            "otm_krs_skv_plan" => $row[ 57 ],
            "otm_krs_skv_fact" => $row[ 58 ],
            "otm_prs_skv_plan" => $row[ 59 ],
            "otm_prs_skv_fact" => $row[ 60 ],
            "cpp_zakachka_para_plan" => $row[ 61 ],
            "cpp_zakachka_para_fact" => $row[ 62 ],
            "fond_neftedob_ef" => $row[ 63 ],
            "fond_neftedob_df" => $row[ 64 ],
            "prod_wells_work" => $row[ 65 ],
            "fond_neftedob_prs" => $row[ 66 ],
            "fond_neftedob_oprs" => $row[ 67 ],
            "fond_neftedob_krs" => $row[ 68 ],
            "fond_neftedob_okrs" => $row[ 69 ],
            "fond_neftedob_well_survey" => $row[ 70 ],
            "fond_neftedob_others" => $row[ 71 ],
            "fond_neftedob_bd" => $row[ 72 ],
            "fond_neftedob_osvoenie" => $row[ 73 ],
            "fond_neftedob_ofls" => $row[ 74 ],
            "fond_neftedob_nrs" => $row[ 75 ],
            "fond_neftedob_prostoy" => $row[ 76 ],
            "fond_neftedob_prostoy_el" => $row[ 77 ],
            "fond_neftedob_svabirovanie" => $row[ 78 ],
            "fond_neftedob_period" => $row[ 79 ],
            "fond_neftedob_vysokoobvod" => $row[ 80 ],
            "fond_nagnetat_ef" => $row[ 81 ],
            "fond_nagnetat_df" => $row[ 82 ],
            "inj_wells_work" => $row[ 83 ],
            "fond_nagnetat_prs" => $row[ 84 ],
            "fond_nagnetat_oprs" => $row[ 85 ],
            "fond_nagnetat_krs" => $row[ 86 ],
            "fond_nagnetat_okrs" => $row[ 87 ],
            "fond_nagnetat_well_survey" => $row[ 88 ],
            "fond_nagnetat_others" => $row[ 89 ],
            "fond_nagnetat_bd" => $row[ 90 ],
            "fond_nagnetat_osvoenie" => $row[ 91 ],
            "fond_nagnetat_ofls" => $row[ 92 ],
            "fond_nagnetat_konv" => $row[ 93 ],
            "fond_nagnetat_ostanovka" => $row[ 94 ],
            "fond_nagnetat_neftedob_fls" => $row[ 95 ],
            "fond_nagnetat_neftedob_konserv" => $row[ 96 ],
            "chem_prod_zakacka_demulg_amount" => $row[ 97 ],
            "chem_prod_zakacka_demulg_plan" => $row[ 98 ],
            "chem_prod_zakacka_demulg_fact" => $row[ 99 ],
            "chem_prod_zakacka_bakteracid_amount" => $row[ 100 ],
            "chem_prod_zakacka_bakteracid_plan" => $row[ 101 ],
            "chem_prod_zakacka_bakteracid_fact" => $row[ 102 ],
            "chem_prod_zakacka_ingibator_korrozin_amount" => $row[ 103 ],
            "chem_prod_zakacka_ingibator_korrozin_plan" => $row[ 104 ],
            "chem_prod_zakacka_ingibator_korrozin_fact" => $row[ 105 ],
            "chem_prod_zakacka_ingibator_soleotloj_amount" => $row[ 106 ],
            "chem_prod_zakacka_ingibator_soleotloj_plan" => $row[ 107 ],
            "chem_prod_zakacka_ingibator_soleotloj_fact" => $row[ 108 ],
            "tb_personal_plan" => $row[ 109 ],
            "tb_personal_fact" => $row[ 110 ],
            "tb_accident_total" => $row[ 111 ],
            "tb_accident_death" => $row[ 112 ],
            "tb_covid_prev_day" => $row[ 113 ],
            "tb_covid_total" => $row[ 114 ],
            "gas_plan" => $row[ 115 ],
            "gas_fact" => $row[ 116 ],
            "liq_plan" => $row[ 117 ],
            "liq_fact" => $row[ 118 ],
            "inj_wells_idle" => $row[ 119 ],
            "prod_wells_idle"=> $row[ 120 ],
            "tb_covid_recover" => $row[ 121 ],
            "__time" => (\PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($row[ 0 ]))->getTimestamp()*1000,
            
        ]);
    }
}
