<?php

namespace App\Imports;

use App\Models\Paegtm\DzoAegtm;
use Maatwebsite\Excel\Concerns\ToModel;
use Carbon\Carbon;
use Maatwebsite\Excel\Concerns\WithStartRow;
use PhpOffice\PhpSpreadsheet\Shared\Date;


class PaegtmDzoAegtmImport implements ToModel, WithStartRow
{

    const COLUMNS = [
        'org_name' => 0,
        'org_name_short' => 1,
        'date' => 2,
        'oil_prod_plan' => 3,
        'oil_prod_fact' => 4,
        'base_oil_prod_plan' => 5,
        'base_oil_prod_fact' => 6,
        'gtm_oil_prod_plan' => 7,
        'gtm_oil_prod_fact' => 8,
        'vns_plan_total' => 9,
        'vns_fact_total' => 10,
        'vns_prod_plan_total' => 11,
        'vns_prod_fact_total' => 12,
        'vns_plan' => 13,
        'vns_fact' => 14,
        'vns_prod_plan' => 15,
        'vns_prod_fact' => 16,
        'vns_grp_plan' => 17,
        'vns_grp_fact' => 18,
        'vns_grp_prod_plan' => 19,
        'vns_grp_prod_fact' => 20,
        'gs_plan' => 21,
        'gs_fact' => 22,
        'gs_prod_plan' => 23,
        'gs_prod_fact' => 24,
        'zbs_plan' => 25,
        'zbs_fact' => 26,
        'zbs_prod_plan' => 27,
        'zbs_prod_fact' => 28,
        'zbgs_plan' => 29,
        'zbgs_fact' => 30,
        'zbgs_prod_plan' => 31,
        'zbgs_prod_fact' => 32,
        'grp_plan' => 33,
        'grp_fact' => 34,
        'grp_prod_plan' => 35,
        'grp_prod_fact' => 36,
        'pvlg_plan' => 37,
        'pvlg_fact' => 38,
        'pvlg_prod_plan' => 39,
        'pvlg_prod_fact' => 40,
        'pvr_plan' => 41,
        'pvr_fact' => 42,
        'pvr_prod_plan' => 43,
        'pvr_prod_fact' => 44,
        'gs_grp_plan' => 45,
        'gs_grp_fact' => 46,
        'gs_grp_prod_plan' => 47,
        'gs_grp_prod_fact' => 48,
        'deepening_plan' => 49,
        'deepening_fact' => 50,
        'deepening_prod_plan' => 51,
        'deepening_prod_fact' => 52,
        'grp_skin_plan' => 53,
        'grp_skin_fact' => 54,
        'grp_skin_prod_plan' => 55,
        'grp_skin_prod_fact' => 56,
        'perestrel_plan' => 57,
        'perestrel_fact' => 58,
        'perestrel_prod_plan' => 59,
        'perestrel_prod_fact' => 60,
        'dostrel_plan' => 61,
        'dostrel_fact' => 62,
        'dostrel_prod_plan' => 63,
        'dostrel_prod_fact' => 64,
        'vbd_plan' => 65,
        'vbd_fact' => 66,
        'vbd_prod_plan' => 67,
        'vbd_prod_fact' => 68,
        'opl_plan' => 69,
        'opl_fact' => 70,
        'opl_prod_plan' => 71,
        'opl_prod_fact' => 72,
        'transfer_to_oil_plan' => 73,
        'transfer_to_oil_fact' => 74,
        'transfer_to_oil_prod_plan' => 75,
        'transfer_to_oil_prod_fact' => 76,
        'uecn_plan' => 77,
        'uecn_fact' => 78,
        'uecn_prod_plan' => 79,
        'uecn_prod_fact' => 80,
        'pvlg_pri_prs_plan' => 81,
        'pvlg_pri_prs_fact' => 82,
        'pvlg_pri_prs_prod_plan' => 83,
        'pvlg_pri_prs_prod_fact' => 84,
        'vpp_plan' => 85,
        'vpp_fact' => 86,
        'vpp_prod_plan' => 87,
        'vpp_prod_fact' => 88,
        'pfp_plan' => 89,
        'pfp_fact' => 90,
        'pfp_prod_plan' => 91,
        'pfp_prod_fact' => 92,
        'tgrp_plan' => 93,
        'tgrp_fact' => 94,
        'tgrp_prod_plan' => 95,
        'tgrp_prod_fact' => 96,
        'vns_oper_plan' => 97,
        'vns_oper_fact' => 98,
        'vns_oper_prod_plan' => 99,
        'vns_oper_prod_fact' => 100,
        'vns_nn_plan' => 101,
        'vns_nn_fact' => 102,
        'vns_nn_prod_plan' => 103,
        'vns_nn_prod_fact' => 104,
        'vns_nn_oper_plan' => 105,
        'vns_nn_oper_fact' => 106,
        'vns_nn_oper_prod_plan' => 107,
        'vns_nn_oper_prod_fact' => 108,
        'idn_plan' => 109,
        'idn_fact' => 110,
        'idn_prod_plan' => 111,
        'idn_prod_fact' => 112,

        'vns_prod_plan_chart'  => 113,
        'vns_prod_fact_chart'  => 114,
        'vns_plan_chart'  => 115,
        'vns_fact_chart'  => 116,
        'gtm_prod_plan_chart'  => 117,
        'gtm_prod_fact_chart'  => 118,
        'gtm_plan_chart'  => 119,
        'gtm_fact_chart'  => 120,
    ];

    /**
     * @return int
     */
    public function startRow(): int
    {
        return 2;
    }

    public function transformDate($value, $format = 'd.m.Y')
    {
        if (empty($value)) {
            return null;
        }
        try {
            return Carbon::instance(\PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($value));
        } catch (\ErrorException $e) {
            return Carbon::createFromFormat($format, $value);
        }

    }

    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {

        return new DzoAegtm([
            'org_name' => $row[self::COLUMNS['org_name']],
            'org_name_short' => $row[self::COLUMNS['org_name_short']],
            'date' => \PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject($row[self::COLUMNS['date']]),
            'oil_prod_plan' => $row[self::COLUMNS['oil_prod_plan']],
            'oil_prod_fact' => $row[self::COLUMNS['oil_prod_fact']],
            'base_oil_prod_plan' => $row[self::COLUMNS['base_oil_prod_plan']],
            'base_oil_prod_fact' => $row[self::COLUMNS['base_oil_prod_fact']],
            'gtm_oil_prod_plan' => $row[self::COLUMNS['gtm_oil_prod_plan']],
            'gtm_oil_prod_fact' => $row[self::COLUMNS['gtm_oil_prod_fact']],
            'vns_plan_total' => $row[self::COLUMNS['vns_plan_total']],
            'vns_fact_total' => $row[self::COLUMNS['vns_fact_total']],
            'vns_prod_plan_total' => $row[self::COLUMNS['vns_prod_plan_total']],
            'vns_prod_fact_total' => $row[self::COLUMNS['vns_prod_fact_total']],
            'vns_plan' => $row[self::COLUMNS['vns_plan']],
            'vns_fact' => $row[self::COLUMNS['vns_fact']],
            'vns_prod_plan' => $row[self::COLUMNS['vns_prod_plan']],
            'vns_prod_fact' => $row[self::COLUMNS['vns_prod_fact']],
            'vns_grp_plan' => $row[self::COLUMNS['vns_grp_plan']],
            'vns_grp_fact' => $row[self::COLUMNS['vns_grp_fact']],
            'vns_grp_prod_plan' => $row[self::COLUMNS['vns_grp_prod_plan']],
            'vns_grp_prod_fact' => $row[self::COLUMNS['vns_grp_prod_fact']],
            'gs_plan' => $row[self::COLUMNS['gs_plan']],
            'gs_fact' => $row[self::COLUMNS['gs_fact']],
            'gs_prod_plan' => $row[self::COLUMNS['gs_prod_plan']],
            'gs_prod_fact' => $row[self::COLUMNS['gs_prod_fact']],
            'zbs_plan' => $row[self::COLUMNS['zbs_plan']],
            'zbs_fact' => $row[self::COLUMNS['zbs_fact']],
            'zbs_prod_plan' => $row[self::COLUMNS['zbs_prod_plan']],
            'zbs_prod_fact' => $row[self::COLUMNS['zbs_prod_fact']],
            'zbgs_plan' => $row[self::COLUMNS['zbgs_plan']],
            'zbgs_fact' => $row[self::COLUMNS['zbgs_fact']],
            'zbgs_prod_plan' => $row[self::COLUMNS['zbgs_prod_plan']],
            'zbgs_prod_fact' => $row[self::COLUMNS['zbgs_prod_fact']],
            'grp_plan' => $row[self::COLUMNS['grp_plan']],
            'grp_fact' => $row[self::COLUMNS['grp_fact']],
            'grp_prod_plan' => $row[self::COLUMNS['grp_prod_plan']],
            'grp_prod_fact' => $row[self::COLUMNS['grp_prod_fact']],
            'pvlg_plan' => $row[self::COLUMNS['pvlg_plan']],
            'pvlg_fact' => $row[self::COLUMNS['pvlg_fact']],
            'pvlg_prod_plan' => $row[self::COLUMNS['pvlg_prod_plan']],
            'pvlg_prod_fact' => $row[self::COLUMNS['pvlg_prod_fact']],
            'pvr_plan' => $row[self::COLUMNS['pvr_plan']],
            'pvr_fact' => $row[self::COLUMNS['pvr_fact']],
            'pvr_prod_plan' => $row[self::COLUMNS['pvr_prod_plan']],
            'pvr_prod_fact' => $row[self::COLUMNS['pvr_prod_fact']],

            'gs_grp_plan' => $row[self::COLUMNS['gs_grp_plan']],
            'gs_grp_fact' => $row[self::COLUMNS['gs_grp_fact']],
            'gs_grp_prod_plan' => $row[self::COLUMNS['gs_grp_prod_plan']],
            'gs_grp_prod_fact' => $row[self::COLUMNS['gs_grp_prod_fact']],
            'deepening_plan' => $row[self::COLUMNS['deepening_plan']],
            'deepening_fact' => $row[self::COLUMNS['deepening_fact']],
            'deepening_prod_plan' => $row[self::COLUMNS['deepening_prod_plan']],
            'deepening_prod_fact' => $row[self::COLUMNS['deepening_prod_fact']],
            'grp_skin_plan' => $row[self::COLUMNS['grp_skin_plan']],
            'grp_skin_fact' => $row[self::COLUMNS['grp_skin_fact']],
            'grp_skin_prod_plan' => $row[self::COLUMNS['grp_skin_prod_plan']],
            'grp_skin_prod_fact' => $row[self::COLUMNS['grp_skin_prod_fact']],
            'perestrel_plan' => $row[self::COLUMNS['perestrel_plan']],
            'perestrel_fact' => $row[self::COLUMNS['perestrel_fact']],
            'perestrel_prod_plan' => $row[self::COLUMNS['perestrel_prod_plan']],
            'perestrel_prod_fact' => $row[self::COLUMNS['perestrel_prod_fact']],
            'dostrel_plan' => $row[self::COLUMNS['dostrel_plan']],
            'dostrel_fact' => $row[self::COLUMNS['dostrel_fact']],
            'dostrel_prod_plan' => $row[self::COLUMNS['dostrel_prod_plan']],
            'dostrel_prod_fact' => $row[self::COLUMNS['dostrel_prod_fact']],
            'vbd_plan' => $row[self::COLUMNS['vbd_plan']],
            'vbd_fact' => $row[self::COLUMNS['vbd_fact']],
            'vbd_prod_plan' => $row[self::COLUMNS['vbd_prod_plan']],
            'vbd_prod_fact' => $row[self::COLUMNS['vbd_prod_fact']],
            'opl_plan' => $row[self::COLUMNS['opl_plan']],
            'opl_fact' => $row[self::COLUMNS['opl_fact']],
            'opl_prod_plan' => $row[self::COLUMNS['opl_prod_plan']],
            'opl_prod_fact' => $row[self::COLUMNS['opl_prod_fact']],
            'transfer_to_oil_plan' => $row[self::COLUMNS['transfer_to_oil_plan']],
            'transfer_to_oil_fact' => $row[self::COLUMNS['transfer_to_oil_fact']],
            'transfer_to_oil_prod_plan' => $row[self::COLUMNS['transfer_to_oil_prod_plan']],
            'transfer_to_oil_prod_fact' => $row[self::COLUMNS['transfer_to_oil_prod_fact']],
            'uecn_plan' => $row[self::COLUMNS['uecn_plan']],
            'uecn_fact' => $row[self::COLUMNS['uecn_fact']],
            'uecn_prod_plan' => $row[self::COLUMNS['uecn_prod_plan']],
            'uecn_prod_fact' => $row[self::COLUMNS['uecn_prod_fact']],
            'pvlg_pri_prs_plan' => $row[self::COLUMNS['pvlg_pri_prs_plan']],
            'pvlg_pri_prs_fact' => $row[self::COLUMNS['pvlg_pri_prs_fact']],
            'pvlg_pri_prs_prod_plan' => $row[self::COLUMNS['pvlg_pri_prs_prod_plan']],
            'pvlg_pri_prs_prod_fact' => $row[self::COLUMNS['pvlg_pri_prs_prod_fact']],
            'vpp_plan' => $row[self::COLUMNS['vpp_plan']],
            'vpp_fact' => $row[self::COLUMNS['vpp_fact']],
            'vpp_prod_plan' => $row[self::COLUMNS['vpp_prod_plan']],
            'vpp_prod_fact' => $row[self::COLUMNS['vpp_prod_fact']],
            'pfp_plan' => $row[self::COLUMNS['pfp_plan']],
            'pfp_fact' => $row[self::COLUMNS['pfp_fact']],
            'pfp_prod_plan' => $row[self::COLUMNS['pfp_prod_plan']],
            'pfp_prod_fact' => $row[self::COLUMNS['pfp_prod_fact']],
            'tgrp_plan' => $row[self::COLUMNS['tgrp_plan']],
            'tgrp_fact' => $row[self::COLUMNS['tgrp_fact']],
            'tgrp_prod_plan' => $row[self::COLUMNS['tgrp_prod_plan']],
            'tgrp_prod_fact' => $row[self::COLUMNS['tgrp_prod_fact']],
            'vns_oper_plan' => $row[self::COLUMNS['vns_oper_plan']],
            'vns_oper_fact' => $row[self::COLUMNS['vns_oper_fact']],
            'vns_oper_prod_plan' => $row[self::COLUMNS['vns_oper_prod_plan']],
            'vns_oper_prod_fact' => $row[self::COLUMNS['vns_oper_prod_fact']],
            'vns_nn_plan' => $row[self::COLUMNS['vns_nn_plan']],
            'vns_nn_fact' => $row[self::COLUMNS['vns_nn_fact']],
            'vns_nn_prod_plan' => $row[self::COLUMNS['vns_nn_prod_plan']],
            'vns_nn_prod_fact' => $row[self::COLUMNS['vns_nn_prod_fact']],
            'vns_nn_oper_plan' => $row[self::COLUMNS['vns_nn_oper_plan']],
            'vns_nn_oper_fact' => $row[self::COLUMNS['vns_nn_oper_fact']],
            'vns_nn_oper_prod_plan' => $row[self::COLUMNS['vns_nn_oper_prod_plan']],
            'vns_nn_oper_prod_fact' => $row[self::COLUMNS['vns_nn_oper_prod_fact']],
            'idn_plan' => $row[self::COLUMNS['idn_plan']],
            'idn_fact' => $row[self::COLUMNS['idn_fact']],
            'idn_prod_plan' => $row[self::COLUMNS['idn_prod_plan']],
            'idn_prod_fact' => $row[self::COLUMNS['idn_prod_fact']],

            'vns_prod_plan_chart'  => $row[self::COLUMNS['vns_prod_plan_chart']],
            'vns_prod_fact_chart'  => $row[self::COLUMNS['vns_prod_fact_chart']],
            'vns_plan_chart'  => $row[self::COLUMNS['vns_plan_chart']],
            'vns_fact_chart'  => $row[self::COLUMNS['vns_fact_chart']],
            'gtm_prod_plan_chart'  => $row[self::COLUMNS['gtm_prod_plan_chart']],
            'gtm_prod_fact_chart'  => $row[self::COLUMNS['gtm_prod_fact_chart']],
            'gtm_plan_chart'  => $row[self::COLUMNS['gtm_plan_chart']],
            'gtm_fact_chart'  => $row[self::COLUMNS['gtm_fact_chart']]

        ]);
    }
}
