import {
    List,
    ListItemDown,
    ListItemUp,
    arrowDown,
    rectArrow,
    success,
    plusAndBrackets,
    plusAndBrackets2,
    remove,
    reload,
    arrowLeft,
    tripleDots,
    rulerToArrow,
    moleqq,
    kern,
    d3,
    geoPh,
    oilTower,
    settPhone,
    lupa, locPC, gisto
} from "./iconsPack.js";

export default {
    ListItemDown,
    List,
    ListItemUp,
    arrowDown,
    rectArrow,
    success,
    plusAndBrackets,
    plusAndBrackets2,
    remove,
    reload,
    arrowLeft,
    tripleDots,
    rulerToArrow,
    moleqq,
    kern, d3, geoPh, oilTower, settPhone,lupa,locPC,gisto
}
