import {u1, welltops, ybs, zone, zoneStatic} from "./chooseStratIcons";

import {
    List,
    ListItemDown,
    ListItemUp,
    arrowDown,
    rectArrow,
    success,
    plusAndBrackets,
    plusAndBrackets2,
    remove,
    reload,
    arrowLeft,
    tripleDots,
    rulerToArrow,
    moleqq,
    kern,
    d3,
    geoPh,
    oilTower,
    settPhone,
    lupa,
    locPC,
    gisto,
    i3d,
    i2d,
    interpret,
    cog,
    cubeArrow,
    eq,
    ruler,
    rightwardsArrow,
    downwardsArrow,
    upwardsArrow,
    copy, returnButton, AppendXYHingeToXSection, AddPaddingToTheXScreen, minus, plus
} from "./iconsPack.js";

export default {
    ListItemDown,
    List,
    ListItemUp,
    arrowDown,
    rectArrow,
    success,
    plusAndBrackets,
    plusAndBrackets2,
    remove,
    reload,
    arrowLeft,
    tripleDots,
    rulerToArrow,
    moleqq,
    kern, d3, geoPh, oilTower, settPhone, lupa, locPC, gisto, i3d, i2d, interpret, cog, cubeArrow, eq, ruler,
    rightwardsArrow,
    downwardsArrow,
    upwardsArrow,
    copy,
    returnButton,
    AppendXYHingeToXSection,
    AddPaddingToTheXScreen,
    minus,
    plus,
    zone,
    u1,
    welltops,
    ybs,
    zoneStatic
}
